### PR TITLE
[# 133297073] Blog Post

### PR DESCRIPTION
**Pull request by subhenduGR**
Blog Post

[Tracker #133297073](https://www.pivotaltracker.com/story/show/133297073)
@richddr @beghbali

### CODE REVIEW

**Comment by alexebird** [comment]
lgtm

**Comment by cobbr2** [comment]
Amusing, Mr Bird.

Rick Cobb / Architect
Grand Rounds
Office: 1-800-929-0926  / Fax: 1-888-323-5997
360 3rd St, Suite 425,  San Francisco, CA 94107
http://www.grandrounds.com ​

**Comment by cobbr2** [comment]
Amusing, Mr. Bird.

Rick Cobb / Architect
Grand Rounds
Office: 1-800-929-0926  / Fax: 1-888-323-5997
360 3rd St, Suite 425,  San Francisco, CA 94107
http://www.grandrounds.com ​

**Comment by glacier** [comment]
I'm still getting this too :)

**Comment by subhenduGR** [comment]
Well, I'm confused with variety of 'reactions'

**Comment by cobbr2** [comment]
Don't be confused -- this is just our way of making sure that the engineers who've left us stay in touch :1 .  They could remove themselves from the project, or point out that we *may* want to make this repo private; they've chosen to do the latter, which is a fine and responsible thing. Hi @glacier and @alexebird :). @abhinavpraneet

**Comment by llachner** [comment]
Miss you @alexebird & @glacier !!

**Comment by soonahn** [comment]
@cobbr2 let's revert this, clean out the commit so we're not showing off our models and schema.

**Comment by soonahn** [comment]
@RoryO @subhenduGR I've reverted this, this shows too much of our data model, as well as how we think about employeers, and encryption.

Let's clean this up.

**Comment by RoryO** [comment]
If we get rid of the output of #inspect on DataSource would that be sufficient?

**Comment by soonahn** [comment]
Just change the words so nothing of ours actually shows up.

**Comment by glacier** [comment]
Hi @cobbr2, @llachner, @soonahn! The reactions are hilarious.

**Pull request merged**
